#!/bin/bash

################################################################################
# Script: webm2mkv
# Description: This script converts a webm video file to Matroska (mkv) format
#              using ffmpeg.
# Usage: webm2mkv <input_file.webm>
# Arguments:
#   <input_file.webm>: The webm video file to be converted to mkv.
# 
# Dependencies: ffmpeg
# Author: João L. Neto (https://github.com/jlnetosci/)
# Date: March 21, 2024
################################################################################

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <input_file.webm>"
    exit 1
fi

# Assign input filename to a variable
input_file="$1"

# Check if the input file exists
if [ ! -f "$input_file" ]; then
    echo "Error: File $input_file not found."
    exit 1
fi

# Remove the extension (.webm) from the input filename
filename="${input_file%.webm}"

# Output filename with .mkv extension
output_file="$filename.mkv"

# Run ffmpeg command to convert webm to mkv
ffmpeg -i "$input_file" -c:v copy -c:a copy "$output_file"

# Check if ffmpeg command was successful
if [ $? -eq 0 ]; then
    echo "Conversion completed: $output_file"
else
    echo "Error: Conversion failed."
fi
